<?php
    $title = 'Edit todo list';
    $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('todo', array('action' => 'edit', 'id' => $this->id)));
    $form->setAttribute('role', 'form');
    $form->prepare();

    echo $this->form()->openTag($form);

    echo $this->formHidden($form->get('id'));
?>
<div class="form-group">
    <?php echo $this->formRow($form->get('name')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('description')); ?>
</div>
    <?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<div class="form-group">
<?php echo $this->form()->closeTag(); ?>